[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
gloo-net = "0.3"
wasm-bindgen-futures = "0.4"

web-sys = { version = "0.3", features = ["console"] }